### ISSUE TITLE
Memory leak + statement has no effect

### ISSUE THREAD

**Issue by MikkoFinell** [Cirrus-Minor/witchblast#13]
Several places throughout the codebase includes this type of problem:

```C++
void KingRatEntity::generateGreenRats()
{
  for (int i = 0; i < 5; i++)
  {
    float xr = x + -100 + rand() % 200;
    float yr = y + -100 + rand() % 200;

    if (xr > TILE_WIDTH * 1.5f && xr < TILE_WIDTH * (MAP_WIDTH - 2)
        && yr > TILE_HEIGHT * 1.5f && yr < TILE_HEIGHT * (MAP_HEIGHT - 2))
    {
      new GreenRatEntity(xr, yr);
    }
    else
      i--;
  }
}
```

`new GreenRatEntity(xr, yr);` Is never deleted, so it will leak memory. Furthermore it's not assigned to an identifier so it literally cannot be used.

Example taken randomly from KingRatEntity.cpp line 310. But exists in several other files as well.

**Comment by Cirrus-Minor** [comment]
Hi Mikko,
thanks for your feedback on the code.
There is no memory leak, there is a mother class for all the entities, and in its constructor, I add the entity to the entity manager.
The entity manager do the update, rendering and Z-sorting of the entities, and it deletes them too.

    GameEntity::GameEntity(float m_x, float m_y)
    {
	// initialize...
	EntityManager::getInstance().add(this);
    }
