### ISSUE TITLE
dev branch does not build due to missing OnlineScoring.h

### ISSUE THREAD

**Issue by akien-mga** [Cirrus-Minor/witchblast#15]
The master branch compiles fine as the online mode is conditional, but in the dev branch the online mode is forced, but src/OnlineScoring.h is missing.

It builds fine when commenting out this line though: https://github.com/Cirrus-Minor/witchblast/blob/448a9bf2004f75a833ed5c826405eba0b7938ab3/src/WitchBlastGame.cpp#L71

Is src/OnlineScoring.h present in .gitignore because it's not freely redistributable? Or because it contains sensitive information about your server? If it's one of those two reasons, I would advise to make the feature opt-in by default, and add a CMake option to toggle it (I could do a PR for that if you want).

**Comment by akien-mga** [comment]
I've added this option to my fork: https://github.com/akien-mga/witchblast/commit/6ceb125ced867b1d418ac54b656a963179f1fc37
I'll wait for your feedback because proposing a PR as I'm not 100% sure I've analysed the situation correctly yet :)

**Comment by Cirrus-Minor** [comment]
Your PR has been merged, I'm clossing the issue.
