### ISSUE TITLE
Mismatched binary/libraries for the Linux release

### ISSUE THREAD

**Issue by silverweed** [Cirrus-Minor/witchblast#17]
Not really a big deal since I can recompile it, but the Linux release is shipping the 2.3.0 version of the libs, while the binary is linked against the 2.2.0 versions, so `sh run.sh` fails with `error while loading shared libraries: libsfml-system.so.2.2.0: cannot open shared object file: No such file or directory`.

I suggest either shipping the 2.2.0 libraries or recompiling the game linking against the 2.3.0 libs :-)

```
$ ldd Witch_Blast 
	linux-vdso.so.1 (0x00007ffe2d49d000)
	libsfml-system.so.2.2.0 => not found
	libsfml-window.so.2.2.0 => not found
	libsfml-graphics.so.2.2.0 => not found
	libsfml-audio.so.2.2.0 => not found
	libsfml-network.so.2.3 => /usr/lib/x86_64-linux-gnu/libsfml-network.so.2.3 (0x00007ff22dc2b000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ff22d91f000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff22d61e000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff22d407000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff22d05e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff22ce41000)
	libsfml-system.so.2.3 => /usr/lib/x86_64-linux-gnu/libsfml-system.so.2.3 (0x00007ff22cc33000)
	/lib64/ld-linux-x86-64.so.2 (0x00005632cc8e8000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007ff22ca2b000)
```

```
$ ls lib/
libsfml-audio.so.2.3.0     libsfml-network.so.2.3.0  libsfml-window.so.2.3.0
libsfml-graphics.so.2.3.0  libsfml-system.so.2.3.0
```

**Comment by Cirrus-Minor** [comment]
Hi silverweed!
The game has been recompiled with 2.2.
Could you please test it ? I don't have a Linux machine here...

Note: the binary version is slightly different of a build done from the GitHub sources, as it is a build with online-scoring (source not available).

**Comment by silverweed** [comment]
I downloaded the new version and it seems libGLEW is missing:
```$ sh run.sh
./Witch_Blast: error while loading shared libraries: libGLEW.so.1.12: cannot open shared object file: No such file or directory
```
which is odd, considering it doesn't even show up among the linked libraries...

**Comment by akien-mga** [comment]
GLEW is a dependency of SFML (among other things), so most likely SFML 2.2 was compiled against GLEW 1.12. You'd need either to install this version if you distrib provides it (sadly GLEW breaks API at each new version, so if you don't have version 1.12, it won't work).

**Comment by silverweed** [comment]
I already have libsfml 2.3 installed, but not libGLEW. Yet I can build and run SFML apps with no problem... (I only have libGL/GLUT on my system)

**Comment by Cirrus-Minor** [comment]
I've updated the archive with the missing lib.
(SFML has been compiled with this version of GLEW in the machine we've used to build the game).
I hope there are no more dependencies!

**Comment by silverweed** [comment]
That fixed it, now it runs flawlessly! ;-)

**Comment by Cirrus-Minor** [comment]
Glad to hear that!
I close the issue now.
