### ISSUE TITLE
Error after compiling

### ISSUE THREAD

**Issue by nifker** [Cirrus-Minor/witchblast#33]
As it finishes compiling I am getting this error:

make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libsfml-window.so', needed by 'Witch_Blast'.  Schluss.
make[2]: *** wait for not finished processes...
[100%] Building CXX object CMakeFiles/Witch_Blast.dir/src/SpiderEggEntity.cpp.o
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/Witch_Blast.dir/all' failed
make[1]: *** [CMakeFiles/Witch_Blast.dir/all] Error 2
Makefile:96: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by nifker** [comment]
I linked all libsfml files in /usr/lib/x86_64-linux-gnu/ to the ones in /usr/lib/ but I am still getting this error:
http://pastebin.com/JNKcCzQM
I have the latest version(9a) of libjpeg installed if it has something with that do.

**Comment by akien-mga** [comment]
You likely need to rebuild SFML against the custom version of libjpeg that you installed.

**Comment by nifker** [comment]
so I uninstalled sfml and jpeg and compiled them and installed jpeg and sfml with "make checkinstall"
now witchblast has a problem with sfml again:

CMake Error at cmake_modules/FindSFML.cmake:97 (FILE):
  file Internal CMake error when trying to open file:
  /usr/include/SFML/Config.hpp for reading.
Call Stack (most recent call first):
  CMakeLists.txt:74 (find_package)


CMake Error at cmake_modules/FindSFML.cmake:307 (message):
  SFML found but version too low (requested: 2.2, found: 1.x)
Call Stack (most recent call first):
  CMakeLists.txt:74 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/user/Schreibtisch/witchblast/CMakeFiles/CMakeOutput.log".
See also "/home/user/Schreibtisch/witchblast/CMakeFiles/CMakeError.log".
user@linux-D397:~/Schreibtisch/witchblast$ cmake .
CMake Error at cmake_modules/FindSFML.cmake:97 (FILE):
  file Internal CMake error when trying to open file:
  /usr/include/SFML/Config.hpp for reading.
Call Stack (most recent call first):
  CMakeLists.txt:74 (find_package)


CMake Error at cmake_modules/FindSFML.cmake:307 (message):
  SFML found but version too low (requested: 2.2, found: 1.x)
Call Stack (most recent call first):
  CMakeLists.txt:74 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/user/Schreibtisch/witchblast/CMakeFiles/CMakeOutput.log".
See also "/home/user/Schreibtisch/witchblast/CMakeFiles/CMakeError.log".

**Comment by akien-mga** [comment]
What version of SFML did you install? Also, make sure to clean your CMakeCache.txt.

**Comment by nifker** [comment]
sfmls CMakeCache.txt or witchblasts? SFML v 2.3.2

**Comment by akien-mga** [comment]
Witchblast's. The output says that you have SFML 1.x, so either it's completely confused by a broken cache, or you also have 1.x installed in a path with a higher priority.

**Comment by nifker** [comment]
Thanks that worked.
